### ISSUE TITLE
Add snapshot testing

### ISSUE THREAD

**Issue by niloysikdar** [leopardslab/react-email#19]
### Description:
1. Setup snapshot testing for the project using Storyshots
    [https://storybook.js.org/addons/@storybook/addon-storyshots](https://storybook.js.org/addons/@storybook/addon-storyshots)

### Outcome:
1. Successfully passed tests for the Email component

**Comment by agentmilindu** [comment]
pleas add your new findings here

**Comment by niloysikdar** [comment]
Opened issue #90 which closes this issue.

CC @agentmilindu
