### ISSUE TITLE
Commitizen support and adding ".npmignore"

### ISSUE THREAD

**Issue by niloysikdar** [leopardslab/react-email#24]
### Description:
1. Adding commitizen support for better commit messages
    [https://www.npmjs.com/package/commitizen](https://www.npmjs.com/package/commitizen)
2. Adding a ".npmignore" file to avoid few files and folders while deploying to npm
3. Adding a git hook for commit style checks

### Outcome:
1. commitizen support
2. well configured ".npmignore" file
3. working git hook for commit style checks

**Comment by agentmilindu** [comment]
Relates to https://github.com/leopardslab/react-email/issues/15
